// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NTİerMapping.DAL;

#nullable disable

namespace NTİerMapping.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241028090139_four")]
    partial class four
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NTierMapping.DATA.Film", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilmAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("IzlenmeSayisi")
                        .HasColumnType("int");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedData")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonYayinlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("KategoriId");

                    b.ToTable("Filmler");
                });

            modelBuilder.Entity("NTierMapping.DATA.FilmDetay", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilmDetayi")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedData")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("FilmId")
                        .IsUnique();

                    b.ToTable("FilmDetaylari");
                });

            modelBuilder.Entity("NTierMapping.DATA.FilmKategori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ModifiedData")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("FilmKategorileri");
                });

            modelBuilder.Entity("NTierMapping.DATA.Oyuncu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hayati")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedData")
                        .HasColumnType("datetime2");

                    b.Property<string>("OyuncuAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Oyuncular");
                });

            modelBuilder.Entity("NTierMapping.DATA.OyuncuFilm", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CalismaGunu")
                        .HasColumnType("int");

                    b.Property<int>("FilmID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedData")
                        .HasColumnType("datetime2");

                    b.Property<int>("OyuncuID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FilmID");

                    b.HasIndex("OyuncuID");

                    b.ToTable("OyuncuFilm");
                });

            modelBuilder.Entity("NTierMapping.DATA.Film", b =>
                {
                    b.HasOne("NTierMapping.DATA.FilmKategori", "FilmKategorisi")
                        .WithMany("KategorininFilmleri")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmKategorisi");
                });

            modelBuilder.Entity("NTierMapping.DATA.FilmDetay", b =>
                {
                    b.HasOne("NTierMapping.DATA.Film", "DetayinFilmi")
                        .WithOne("FilminDetayi")
                        .HasForeignKey("NTierMapping.DATA.FilmDetay", "FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetayinFilmi");
                });

            modelBuilder.Entity("NTierMapping.DATA.OyuncuFilm", b =>
                {
                    b.HasOne("NTierMapping.DATA.Film", "OyuncununFilmi")
                        .WithMany("FilminOyunculari")
                        .HasForeignKey("FilmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NTierMapping.DATA.Oyuncu", "FilminOyuncusu")
                        .WithMany("OyuncununFilmleri")
                        .HasForeignKey("OyuncuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilminOyuncusu");

                    b.Navigation("OyuncununFilmi");
                });

            modelBuilder.Entity("NTierMapping.DATA.Film", b =>
                {
                    b.Navigation("FilminDetayi")
                        .IsRequired();

                    b.Navigation("FilminOyunculari");
                });

            modelBuilder.Entity("NTierMapping.DATA.FilmKategori", b =>
                {
                    b.Navigation("KategorininFilmleri");
                });

            modelBuilder.Entity("NTierMapping.DATA.Oyuncu", b =>
                {
                    b.Navigation("OyuncununFilmleri");
                });
#pragma warning restore 612, 618
        }
    }
}
